### ISSUE TITLE
Supervisors are introduced with unsuitable exemplary use cases

### ISSUE THREAD

**Issue by sternmull** [elixir-lang/elixir-lang.github.com#1039]
The guide uses a key-value registry as example for the supervised processes. The hex docs for the Supervisor module use a GenServer that implements a stack. In both cases the state that is managed by  the child processes is probably critical to the application. Nonetheless they will just restart with their initial state when they crash. Applications that rely on the integrity of that state would probably start to do strange things.
I think a better example would be a cache, or something that provides a service and not a state.

**Comment by josevalim** [comment]
@sternmull hi!

There is nothing stopping a stack or a key-value registry for being used to keep temporary information. For example, Mix, the build tool that ships with Elixir, uses a stack to keep information about the projects being compiled. If the VM crashes, the stack is lost, but we don't care because the information the stack was tracking won't matter anyway.

Also remember the state in processes is not shared! Part of the benefits behind supervision trees is so the relevant parts of your application are restarted in case of crashes. Therefore, if a process restarts and it loses some state, your system should go back to a working state, it should not "start to do strange things", because the system is wired up in a way dependent parts restarts in case of crashes.

It is a very common for new developers to wonder what to do with the state of the processes when there are crashes. But the counter-point is: why would your process crash in the first place? The crash should happen on unexpected scenarios... maybe the crash even happened because the state got corrupted some operations before... and trying to persist this state will simply cause the crash to happen over and over again.

I am not sure if this rambling is helping but you shouldn't necessarily consider that all state in processes need to be persisted. The restarts exist exactly to bring your system back to a working place in case of unexpected scenarios. Like when you turn your printer off and on when it refuses to print. Or how you restart your browser when things are weird. If you are worried about persistence, it is more useful to ask "do I want this data to be here if I restart the whole node or when a new node comes up?" then you design your system around that data source... and it is still unlikely that the data source will be a direct dump of your process state.

**Comment by sternmull** [comment]
@josevalim thanks!

Yes, i am new to elixir. Seeing the examples in isolation made me think about the state-owning processes like containers in other languages... that will silently reset if something goes wrong. But reading your explanation i probably should think about them as part of many connected processes that are configured to restart in a reasonable way if one of them crashes. This way it makes sense.

Thanks for taking the time for the explanation!
