### ISSUE TITLE
Improve discoverability of "with" syntax

### ISSUE THREAD

**Issue by adamniedzielski** [elixir-lang/elixir-lang.github.com#1068]
Yesterday I was searching for examples how `with` syntax works in Elixir. I've heard about it before, but I haven't used it so far.

When you type in "elixir with syntax" into Google you'll get at least a few blog posts showing how to use it, but I struggled to find "official" documentation for it. I expected to find something about it in http://elixir-lang.github.io/getting-started/case-cond-and-if.html because it seems related, but it's not there. After some time I found https://hexdocs.pm/elixir/Kernel.SpecialForms.html#with/1 which is exactly what I was looking for.

The thing is: I knew that `with` exists. From a point of view of someone who doesn't know about it at all, discovering `with` in the official documentation is quite unlikely. I think that we can improve this situation.

Please let me know if I'm missing something or if you have suggestions how to better document `with`.

**Comment by josevalim** [comment]
I am not sure how we can make keywords such as "with" and "for" more discoverable. I don't think we should add it to the getting started guide because the guide is not a reference, it is focused on teaching. If we start to make it feel like are reference, then those learning the language will get side-tracked all the time instead of focusing pn the basic constructs.

The proper place to search for it would be on hexdocs.pm but I am not sure how we can make it clearer.

**Comment by adamniedzielski** [comment]
Thanks for the response. I totally get your argument with keeping the getting started guide focused on basic constructs. I also don't have a good idea how to make easier to discover 😞.

Currently there are 3 sections in the getting started guides - "Getting started", "Mix and OTP" and "Meta-programming in Elixir". Maybe adding a fourth one, something like "Extended syntax" could be an option 🤔.

**Comment by josevalim** [comment]
Well, "extended syntax" in this case is really special forms and we already have a page in the docs that lists all special forms... no?

**Comment by josevalim** [comment]
I don't think there is much we can do here. If anyone has further suggestions, please let us know. Thanks!
