### ISSUE TITLE
Unclear how to setup routing table in "Assembling multiple releases"

### ISSUE THREAD

**Issue by abstractcoder** [elixir-lang/elixir-lang.github.com#1370]
I just finished working through the Mix and OTP guide. At the end of the "Assembling multiple releases" section of "Configuration and releases" page its unclear on how to setup the routing table to get the foo and bar releases to work, so the app is left in an unworking state. The "Configuring releases" section alludes to reading a routing table from disk but I'm still unsure how to proceed.

**Comment by josevalim** [comment]
I don't think configuring the routing table is a good idea because you can end-up with cycles and what not but here is how you would do this. Your `config/releases.exs` would be written like this:

```elixir
import Config
{table, _} = Code.eval_file("routing_table_from_disk.exs")
config :kv, :routing_table, table
```

Where "routing_table_from_disk.exs" is a file at the root of your release. You can add files at the root of your release using rel/overlays available in Elixir v1.10. Add this:

```elixir
# rel/overlays/routing_table_from_disk.exs
[
  {?a..?m, :"foo@computer-name"},
  {?n..?z, :"bar@computer-name"}
]
```

And you should be good to go! I will simplify that section for now. Thanks!
