### ISSUE TITLE
getting started: basic types: h

### ISSUE THREAD

**Issue by jtagcat** [elixir-lang/elixir-lang.github.com#1443]
https://elixir-lang.org/getting-started/basic-types.html#identifying-functions-and-documentation

I think it should be hinted, that bash equivalent is `man round(1)`. Thoughts? PR welcome?

Is there any place for discussion around the homepage?

**Comment by josevalim** [comment]
We usually don’t do a lot of external comparisons because they are always relative. What if someone is coming from Windows? Or have limited terminal experience? So we do our best to explain things in our own terms. Thanks!

PS: discussion about the home page can happen in the Elixir-Lang mailing list. :)
