### ISSUE TITLE
Project showcase nomination process?

### ISSUE THREAD

**Issue by unnawut** [elixir-lang/elixir-lang.github.com#1461]
## Context

Our team just stumbled upon https://elixir-lang.org/cases.html and thought that we could contribute by highlighting how Elixir enabled us to do heavy concurrency and supervision in our project, namely [`elixir-omg`](https://github.com/omgnetwork/elixir-omg) and [`omg-childchain-v1`](https://github.com/omgnetwork/omg-childchain-v1).

Some of our Elixir/BEAM usages:

- Concurrency with [a dozen of GenServers](https://github.com/omgnetwork/elixir-omg/blob/master/apps/omg_watcher/lib/omg_watcher/sync_supervisor.ex) and message passing
- Limit and recover from unexpected failures with `Supervisor` and [supervision tree](https://github.com/omgnetwork/omg-childchain-v1/blob/master/apps/omg_child_chain/lib/omg_child_chain/supervisor.ex#L53-L72)
- [Periodic tasks](https://github.com/omgnetwork/omg-childchain-v1/blob/master/apps/omg_child_chain/lib/omg_child_chain/block_queue/submission_monitor.ex)
- [Collect and emit metrics](https://github.com/omgnetwork/elixir-omg/search?q=telemetry) (`:ets` and also `:telemetry`)
- [Monitoring and alarms](https://github.com/omgnetwork/omg-childchain-v1/blob/master/apps/omg_child_chain/lib/omg_child_chain/monitor.ex)
- [Multiple release targets](https://github.com/omgnetwork/elixir-omg/blob/master/mix.exs#L28-L101)

All of these would've been much more complex without Elixir and BEAM. 

## Question

How best should we nominate our project for inclusion into https://elixir-lang.org/cases.html? We'll be happy to do the write up and let you review!

**Comment by josevalim** [comment]
Hi @unnawut! Thanks for reaching out to us!

It is impossible for us to ever feature all of the usage in the Elixir community, so our recommendation is for companies to go ahead and write about their usage and do not wait for us. :) 

The cases so far have been selected based on different factors, such as industries, scale, and technologies used, as we want to highlight variety of companies and solutions in the ecosystem. For now, it has been invitation only by me, which I understand is somewhat limiting, but since this is something relatively new for us, I want to be involved in all steps of the process.

You should also consider the [Running in Production](https://runninginproduction.com/tags/elixir) podcast, they cover different stacks, Elixir being one of them. /cc @nickjj

**Comment by unnawut** [comment]
Very well noted thanks!

**Comment by nickjj** [comment]
Thanks for the CC.

As for Running in Production, if you're using Elixir in the context of running a web application I'd be happy to have you on. We'd spend about an hour talking about building and deploying your app, along with going over things like tips and lessons learned.

If that sounds good and you want to come on the show, you can [fill out this form](https://docs.google.com/forms/d/e/1FAIpQLSdaCRorXztETX1rQxcYT67OTkF3BKb-max99RYpRPrEiO-sKw/viewform) to get the ball rolling.

**Comment by unnawut** [comment]
@nickjj Sounds good, will do! Thanks!
