### ISSUE TITLE
Is anything being done about the Elixir logo situation?

### ISSUE THREAD

**Issue by nathanchere** [elixir-lang/elixir-lang.github.com#1487]
This has been the ongoing answer for at least 5-6 six years, e.g. https://github.com/elixir-lang/elixir-lang.github.com/issues/575

Is there anything blocking this? Or is it even seriously being pursued at all? I'm mostly asking because I find it strange that FontAwesome still doesn't include an Elixir logo despite including an Phoenix one and the team even stating they are "big fans of Elixir" (https://twitter.com/fontawesome/status/1009847695408816129)

I would rather a clear and explicit "no, it's not going to happen in any foreseeable future" if that's the case.

**Comment by josevalim** [comment]
The situation is still the same. We have no updates from the Brazilian trademark offices and I assume COVID doesn't help either. I was told though it will be approved, that we just have to be patient. Believe me, I would prefer if this would have already been addressed. :(

Given I do not have timeline for it,  "no, it's not going to happen in any foreseeable future" is indeed the best I can offer.

Btw, I will go ahead and lock this, because people have used this topic to be rude in the past, but I don't mind answering questions to this when it is done politely as yours. :) Have a good weekend!
