### ISSUE TITLE
Translating Elixir Guides

### ISSUE THREAD

**Issue by matreyes** [elixir-lang/elixir-lang.github.com#1657]
Hi team!

We were discussing in the Elixir Chile community that even if english is a must for developers, younger people could be overwhelmed learning english and to code at the same time. So having documentation like the Elixir Guides in Spanish could be great for newcomers. 

If we translate the guides to Spanish. Would you like to include them in the official site or you prefer if we have a separate site forked from elixir-lang ? (We are aware that maintaining translations could be a headache).

Best.

**Comment by josevalim** [comment]
Hi @matreyes! Thanks for reaching out!

My plan is to actually move the guides to the Elixir language repository so they are backed by ExDoc, which means that a separate repository for the guides would be best. So I don't want to take momentum away, but holding a bit with the translation may be best because you could generate your own translated pages with ExDoc too. :)

**Comment by josevalim** [comment]
Oops, I will leave this open until migration is done!

**Comment by matreyes** [comment]
That sounds great! Meanwhile we can advance with the translations in markdown so they can be used when the migration is ready.

**Comment by josevalim** [comment]
This is on the way. You can find the converted guides, as we work on them, on the Elixir repo.
