### ISSUE TITLE
More mix examples about compilation and execution of code

### ISSUE THREAD

**Issue by ararog** [elixir-lang/elixir-lang.github.com#415]
Today I created a very basic project using mix, I used Urna as dependency to create a module which I saved on resources folder created inside project structure.

~No matter what I tried, I never could compile the file created, should I have to place the file inside lib folder to get compiled, what if I place the file in a non standard folder? How can I get the module contained on this file compiled? More than that, how can I execute the binary generated considering that I'm using Urna as dependency?~

It would be nice to have more detailed examples on how to perform these tasks, since they aren't easy to find out right now.

Thanks!

**Comment by josevalim** [comment]
Thanks for the feedback!

It is always hard to know what to keep and what to remove from the guides. Since it is not meant to be a complete reference, we need to find the right balance without being too long or too short. That said, we will your feedback in mind and add other sections in the future if users are coming across the same issue.

In any case, don't hesitate to ask on stack overflow, the mailing list or on irc too. Finally, you can compile any directory you want by setting `[elixirc_paths: ["lib", "resources"]]` in your `mix.exs` file. Try `mix help compile.elixir` in your terminal for more information.
