### ISSUE TITLE
Vector Logo

### ISSUE THREAD

**Issue by gilbarbara** [elixir-lang/elixir-lang.github.com#575]
Hello,

Do you have the elixir in a vector format? I'd love to add it here: https://github.com/gilbarbara/logos (a.k.a. http://svgporn.com/)

:grin:

**Comment by josevalim** [comment]
Unfortunately we do not have one yet to make available, hopefully soon!

**Comment by gilbarbara** [comment]
:+1:

**Comment by tomekwi** [comment]
Just found one here, whoever made it 🤔 

http://plataformatec.com.br/elixir-radar/images/elixir-drop-b99a65e929bd0e991510add4b3b3ddbf.svg

**Comment by josevalim** [comment]
Keep in mind the logo is copyrighted to Plataformatec and you cannot use it without permission. We want to have clear rules for using the logo but we have been advised to do so only after the trademark process is done.

**Comment by gilbarbara** [comment]
👎🏼

**Comment by tomekwi** [comment]
Fair enough, will keep that in mind @josevalim.

**Comment by hongsw** [comment]
Can anyone help me? I need a elixir vector file for sticker. Korean elixir developers want to put their notebooks.

**Comment by danilaml** [comment]
@josevalim why is this issue closed if there are still no official svg logo available (correct me if I'm wrong)?

**Comment by josevalim** [comment]
@danilaml the reason has been given above:

> Keep in mind the logo is copyrighted to Plataformatec and you cannot use it without permission. We want to have clear rules for using the logo but we have been advised to do so only after the trademark process is done.

I understand many would like to use the logo and we would love to allow so but we have been advised to not do so until all legalities are done.

**Comment by danilaml** [comment]
@josevalim well, I guess this is the reason the current logo is not yet available, but the issue is still there. I think it should be fixed either then some form of the logo becomes available or there is a definite resolution that it won't and can't be.

Btw, is there any correct way to refer to the Elixir in a logo-like form without infringing on anyone's copyright?

**Comment by ericmj** [comment]
> well, I guess this is the reason the current logo is not yet available, but the issue is still there. I think it should be fixed either then some form of the logo becomes available or there is a definite resolution that it won't and can't be.

Given what Jose said the logo won't and can't be available until the trademark process if finished. When the trademark process is finished the rules of using the logo will be looked at again.

> Btw, is there any correct way to refer to the Elixir in a logo-like form without infringing on anyone's copyright?

Right now it's best if you don't use the logo.

**Comment by josevalim** [comment]
To add to what @ericmj said, our issues tracker usually keep issues that we or the community can act on. If the issue does not have short or medium term plan for execution, then it does not belong to the issues tracker. This is to keep the tracker focused on actionable items.

**Comment by danilaml** [comment]
Ok, got it. Thanks. By chance, is there any ETA on the trademark process. Don't know how long they usually take, but it's been almost half a year since it's been mentioned in this issue and the issue itself  is almost two years old. Would be sad if it takes another two years to resolve any possible issues.

**Comment by josevalim** [comment]
I don't want to give an ETA to not create any expectations for something that is completely out of my control.

**Comment by gilbarbara** [comment]
LOL

**Comment by josevalim** [comment]
@gilbarbara if you agree or disagree with something, feel free to elaborate your points besides "LOL". If all you have is a reaction, then use the proper reaction features. Otherwise it is rude to pollute the inbox of maintainers and contributors while we do have actual work to do.

Finally I would like to add that copyright and trademark requirements of logos is fairly common across technologies. Here are some examples that are very well documented:

  * https://nodejs.org/en/about/trademark/
  * https://www.apache.org/foundation/marks/

The trouble is that we are not allowed to release the logo and such documents until the process is done. We have no ETA as the process is happening in multiple countries.

**Comment by henriqueioneda** [comment]
@josevalim How can I ask for permission to use the logo? I am doing a presentation with the theme "Introduction to Elixir" and I'd like to use Elixir's logo.

**Comment by maennchen** [comment]
@josevalim Is there a clear legal situation by now?

**Comment by jamiecurle** [comment]
Is the creative commons license on this file correct?

https://commons.wikimedia.org/wiki/File:Official_Elixir_logo.png

**Comment by njwest** [comment]
I am also curious about logo usage, I am trying to cultivate an Elixir community here in Hong Kong (where everything still runs on PHP) and would love to promote Elixir online using the official logo

**Comment by nicklayb** [comment]
While it may sounds like a dumb question, does the copyright prevent myself from making a really nice custom mug for my office, for my private usage? (I have an obsession for tech mugs)

Basically my question is: Can I use the logo for custom merch I keep for myself?

**Comment by sarat1669** [comment]
@josevalim any update on this?

**Comment by josevalim** [comment]
We did get the trademark for the logo in Brasil under some classes, so there has been some progress, but the process unfortunately has not been finished yet (and it is happening in more than one country).

**Comment by AgaAgnieszkaBorcz** [comment]
@josevalim  Hi any update on Elixir Logo use? much appreciated

**Comment by josevalim** [comment]
@AgaAgnieszkaBorcz the update above is the most recent news we have. We are still waiting for the process(es) to finish.

PS: please avoid opening and pinging on multiple issues.

**Comment by atorresbr** [comment]
> Keep in mind the logo is copyrighted to Plataformatec and you cannot use it without permission. We want to have clear rules for using the logo but we have been advised to do so only after the trademark process is done.

Can anyone use this fucking logo for nothing? (Elixir logo)

**Comment by josevalim** [comment]
More info here: https://elixir-lang.org/trademarks
