### ISSUE TITLE
`if` / `else` `if`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#582]
Should we mention in http://elixir-lang.org/getting-started/case-cond-and-if.html#if-and-unless
the use of `else if`.
I think it's good because in other languages its a special keyword (elif, elseif),
just to let the user know we can do it just by nesting if inside else.

**Comment by whatyouhide** [comment]
I am :-1: because: 

* `if...else if...else` is clearer with `cond`
* many languages do have their special keyword as you mentioned (`elsif`, `elseif`) but many don't (C, JavaScript)
* it's the "getting started" guide so we don't have to provide a complete reference and we're introducing the language to newcomers, so IMO it's better to leave off not-best practices :)

**Comment by eksperimental** [comment]
i completely agree with you @whatyouhide
