### ISSUE TITLE
iex should apparently be called ielixir in the docs

### ISSUE THREAD

**Issue by BruceEckel** [elixir-lang/elixir-lang.github.com#599]
On the page http://elixir-lang.org/getting-started/introduction.html (and I assume other pages) it refers to iex. When I installed elixir using chocolatey, iex was not on my path, but ielixir was.

**Comment by josevalim** [comment]
Thank you @BruceEckel!

@onoriocatenacci can you please confirm this is indeed the way to go?

**Comment by OnorioCatenacci** [comment]
Hi Jose and Bruce,

Actually it's up to you Jose.  I didn't get rid of iex on Windows; I simply added ielixir as a shortcut for the iex.bat file.  That is the only file that I aliased because it's the only one that presents a problem with Powershell.  I mean to say that a person can use the ielixir shortcut from either a powershell terminal window or the old windows cmd terminal window but you can't type "iex" in the Powershell window--you need to type iex.bat.  So I added ielixir as an alternative for that case. 

It only applies when someone downloads the ChocolateyNuGet package and it is just a secondary shortcut; iex.bat and the rest all still work.  I think I can add iex.bat to the path as well--I say "I think" because of the Windows shimming technology I'm using to add the shortcut to ielixir.  I can double check this.

I could swear that I had sent something to the Elixir-Lang-Talk mailing list mentioning this additional shortcut but I can't seem to find it now.

At any rate, this is just a secondary shortcut that I added to the ChocolateyNuGet package--it only applies on Windows and it only applies when someone has run the CNG installer.  And, as I say, I'm not forcing anyone to use ielixir; it's there solely as a convenience for those who want to run Powershell as their terminal console.

What do you think Jose?  I can remove it (as I say I added it because Windows users should be using Powershell for a terminal and when you use Powershell for a terminal iex has a different meaning) or I can see if I can add iex to the path as well.  I could also document it if you want.  

Just let me know how you want to proceed.  Sorry if this caused you any inconvenience Bruce!

--
Onorio

**Comment by OnorioCatenacci** [comment]
By the way Jose if you want me to add iex.bat (and the rest) to the path, I should be able to make that change when I upload the 1.1.0-rc0 CNG package which I should have within the next day or two.

**Comment by BruceEckel** [comment]
Either way, but if the docs say "iex" and it doesn't work for the
chocolatey people (who, I suspect, are expecting a simple install), then it
can potentially turn some people away. I use the out-of-the-box experience
as part of a litmus test, so I think it's important.


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by josevalim** [comment]
Thank you @OnorioCatenacci! Don't worry, you did everything perfect.

@BruceEckel we say `iex.bat` the first time we run iex: http://elixir-lang.org/getting-started/introduction.html

Which part was confusing or unclear? Should we have a large disclaimer?

**Comment by OnorioCatenacci** [comment]
I'll write this up partially to explain my thinking and partially so it's
documented.

1.) Totally agree that out of the box experience is very important.  But
what I've struggled with is what constitutes "out of the box" when someone
is installing from Chocolatey NuGet (CNG).  You can run CNG from either the
terminal window that comes up when you run cmd (cmd_shell) or the terminal
window that comes up when you run powershell (ps_shell).  At the cmd_shell
typing _iex_ if iex.bat is in the path and the erlang runtime is in the
path will work exactly as expected.  But in the ps_shell (and CNG is a
bunch of powershell scripts) typing _iex_ will not start iex.bat but
instead will run the "Invoke-Expression" cmdlet.

Now for most windows apps, you wouldn't even have to start a terminal
window--you'd have a shortcut on the desktop or something on the start menu
or something like that.  But elixir is something that developers (as
opposed to general end-users) use so starting a command line isn't so much
of an issue.  But, as I say, which command line?  cmd_shell or
ps_shell--especially as I say, given that CNG is a bunch of PS scripts and
given that the most likely person to install the Elixir CNG package is a
developer who might prefer ps_shell over cmd_shell.

2.) I don't know about other Windows users but for me, I don't want
applications automatically adding themselves to my path.  This is for two
reasons:

a.) This is my development machine; I don't want the environment changed
unless I change it myself.  Could cause me problems with my development
work.

b.) The path can only be 256 characters long and every app that adds itself
to the path is taking up space in that 256 characters.

Hence I felt that even though the out of the box experience would suffer, I
would avoid automatically appending either Erlang or Elixir's binary
directories to the path.  As I say, again, I'm inclined to believe that
most of the folks looking at Elixir via CNG are developers and while it's a
bit annoying not to have "iex" work out of the box, since they are
developers I would hope they can understand the reasoning. I guess I have
been a bit lax about documenting the reasoning for the choice and
explaining what someone needs to do in order to get it so that "iex" works
as expected at a cmd_shell prompt.

3.) As I say since I primarily use the ps_shell, I got tired of forgetting
to type "iex.bat" as opposed to "iex" so I created the "ielixir" shortcut
so I wouldn't keep forgetting.  I added it to the CNG package as a
convenience for others. But it was an addition; the behavior of iex in
relation to Windows is exactly the same as it was before.  That is someone
still needs to add the Erlang and Elixir binary directories to their path
themselves if they want to run "iex.bat" in the ps_shell.  As I say this is
because I'm guessing that most people looking at this are developers.

4.) I think I should probably make a PR to supplement the docs to explain
exactly what I explained above since this question seems to come up all the
time for those who install the CNG version to play with Elixir.

So having said all that, if you want Jose, I can modify the 1.1.0-rc0 CNG
package to add a shimmed shortcut to iex.bat to the path.  But the problem
with ps_shell will still remain.  And it has been my impression that there
are a lot of sysadmins who are converting to using ps_shell (as opposed to
cmd_shell) on a more regular basis because the scripting language in
ps_shell is a lot more powerful than the old Windows batch files.

If you want me to do a PR for the docs to document my choices for the CNG
package, just let me know.  I'm happy to write this up.  Or maybe a FAQ on
the install packages or something of that sort.  This question about "iex"
not working seems to come up almost as often as why strings are displayed
for lists of chars and why values can be _seemingly_ rebound.


On Wed, Sep 16, 2015 at 4:15 AM, José Valim <notifications@github.com>
wrote:

> Thank you @OnorioCatenacci <https://github.com/OnorioCatenacci>! Don't
> worry, you did everything perfect.
>
> @BruceEckel <https://github.com/BruceEckel> we say iex.bat the first time
> we run iex: http://elixir-lang.org/getting-started/introduction.html
>
> Which part was confusing or unclear? Should we have a large disclaimer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140665551>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by josevalim** [comment]
For Windows, we will always tell users to use `iex.bat`. I believe this is orthogonal to the Chocolatey discussion because that's the only way afaik to run Elixir across all windows shells and installers. That's problem 1: make it clear that Windows users need to run `iex.bat`.

Problem 2: should Chocolatey add things to my PATH, regardless if `iex.bat` or `ielixir`? That's not up to me to answer. I think you should just follow Chocolatey best practices here and Chocolatey users will be aware of what should be done. If we want to keep it as is, without copying, then may be should add a tiny note to the install page under the Chocolatey instructions that says: "Elixir executables are not added to your PATH automatically. Do x, y, z to add them".

**Comment by OnorioCatenacci** [comment]
Ok Jose that makes good sense to me. I can modify the CNG installer, as I
say, when I create the package for 1.1.0-rc0--which should be today around
my lunchtime. :)

On Wed, Sep 16, 2015 at 8:16 AM, José Valim <notifications@github.com>
wrote:

> For Windows, we will always tell users to use iex.bat. I believe this is
> orthogonal to the Chocolatey discussion because that's the only way afaik
> to run Elixir across all windows shells and installers. That's problem 1:
> make it clear that Windows users need to run iex.bat.
>
> Problem 2: should Chocolatey add things to my PATH, regardless if iex.bat
> or ielixir? That's not up to me to answer. I think you should just follow
> Chocolatey best practices here and Chocolatey users will be aware of what
> should be done. If we want to keep it as is, without copying, then may be
> should add a tiny note to the install page under the Chocolatey
> instructions that says: "Elixir executables are not added to your PATH
> automatically. Do x, y, z to add them".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140724439>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
Ok, just to put a final conclusion on this discussion:

1.) I've modified the Elixir 1.1.0-rc0 installer to create a shortcut to
"iex.bat" and I've modified the installer to insure that people are told
they need to type "iex.bat" at the command prompt.

2.) Since "iex.bat" works for both the cmd shell and the powershell shell
there's no need for ielixir and I've removed it.

3.) If you want me to modify the docs to specify "iex.bat" for Windows,
just let me know.  I can do a PR when I get a chance.

4.) I've uploaded the 1.1.0-rc0 CNG package to CNG.  I may make an
announcement later but I sometimes think people get tired of hearing me
announce things :)

--
Onorio


On Wed, Sep 16, 2015 at 8:16 AM, José Valim <notifications@github.com>
wrote:

> For Windows, we will always tell users to use iex.bat. I believe this is
> orthogonal to the Chocolatey discussion because that's the only way afaik
> to run Elixir across all windows shells and installers. That's problem 1:
> make it clear that Windows users need to run iex.bat.
>
> Problem 2: should Chocolatey add things to my PATH, regardless if iex.bat
> or ielixir? That's not up to me to answer. I think you should just follow
> Chocolatey best practices here and Chocolatey users will be aware of what
> should be done. If we want to keep it as is, without copying, then may be
> should add a tiny note to the install page under the Chocolatey
> instructions that says: "Elixir executables are not added to your PATH
> automatically. Do x, y, z to add them".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140724439>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by josevalim** [comment]
3.) If you want me to modify the docs to specify "iex.bat" for Windows,
just let me know. I can do a PR when I get a chance.

We already do this but maybe we should be clearer.
I don't know what to change though.

Thanks for all the changes and improvements Onorio!

**Comment by OnorioCatenacci** [comment]
I'm always glad to do what I can to help Jose.

Take a look at my announcement of the CNG package on Elixir Lang Talk.  We
need to explicitly document that someone needs to type the string "iex.bat"
at a command prompt because on Windows normally you can run a batch file
without having to type the extension.  That is a Windows user would expect
to type "iex" (no extension) and have it run iex.bat.  We've just changed
it such that someone will need to type "iex.bat" (with the extension).
It's down to making it clear that they will need to type the extension
which they normally wouldn't.

--
Onorio


On Wed, Sep 16, 2015 at 9:37 AM, José Valim <notifications@github.com>
wrote:

> 3.) If you want me to modify the docs to specify "iex.bat" for Windows,
> just let me know. I can do a PR when I get a chance.
>
> We already do this but maybe we should be clearer.
> I don't know what to change though.
>
> Thanks for all the changes and improvements Onorio!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140744832>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by BruceEckel** [comment]
The path length appears to be 2047, with 4095 for Windows 7 and later:
https://software.intel.com/en-us/articles/limitation-to-the-length-of-the-system-path-variable

I'm not suggesting whether it be iex or ielixir; just that, once the user
does an installation, whatever the documentation says should work without
additional adjustments to the path.


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by OnorioCatenacci** [comment]
Wow--I guess that shows how long I've been working on Windows.  That about
only 256 chars may even go back to the days of DOS. Good to know that about
the path.

Regardless the CNG package for Elixir 1.1.0-rc.0 now contains a shortcut to
iex.bat.  But you will need to type "iex.bat" (with the file extension) to
start it.  But it's not finished just yet (there are some problems that I
know about) and I hope to have it all fixed up for the Elixir 1.1.0 final
CNG package.


On Wed, Sep 16, 2015 at 12:55 PM, Bruce Eckel <notifications@github.com>
wrote:

> The path length appears to be 2047, with 4095 for Windows 7 and later:
>
> https://software.intel.com/en-us/articles/limitation-to-the-length-of-the-system-path-variable
>
> I'm not suggesting whether it be iex or ielixir; just that, once the user
> does an installation, whatever the documentation says should work without
> additional adjustments to the path.
>
>
> -- Bruce Eckel
> www.MindviewInc.com <http://www.mindviewinc.com/>
> Blog: BruceEckel.github.io
> www.WinterTechForum.com
> www.AtomicScala.com
> www.Reinventing-Business.com
> http://www.TrustOrganizations.com <http://www.ScalaSummit.com>
>
>
> On Wed, Sep 16, 2015 at 7:47 AM, Onorio Catenacci <
> notifications@github.com>
> wrote:
>
> > I'm always glad to do what I can to help Jose.
> >
> > Take a look at my announcement of the CNG package on Elixir Lang Talk. We
> > need to explicitly document that someone needs to type the string
> "iex.bat"
> > at a command prompt because on Windows normally you can run a batch file
> > without having to type the extension. That is a Windows user would expect
> > to type "iex" (no extension) and have it run iex.bat. We've just changed
> > it such that someone will need to type "iex.bat" (with the extension).
> > It's down to making it clear that they will need to type the extension
> > which they normally wouldn't.
> >
> > --
> > Onorio
> >
> >
> > On Wed, Sep 16, 2015 at 9:37 AM, José Valim <notifications@github.com>
> > wrote:
> >
> > > 3.) If you want me to modify the docs to specify "iex.bat" for Windows,
> > > just let me know. I can do a PR when I get a chance.
> > >
> > > We already do this but maybe we should be clearer.
> > > I don't know what to change though.
> > >
> > > Thanks for all the changes and improvements Onorio!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140744832
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Onorio Catenacci
> >
> > http://onor.io
> > http://www.google.com/+OnorioCatenacci
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140747172
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140802499>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
For whatever it's worth, I just discovered why Bruce and I found such
different numbers.  The absolute path to a specific file in Windows can
never be more than 260 characters.
https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath  (The
MAX_PATH constant in the Windows API) This is what I was thinking of when I
mentioned the limit on path length.  As far as I can tell this still holds
with Windows 10 for whatever it's worth.

Bruce is right in that the length limit of the PATH environment variable is
much more than 260 characters and, of course, it's referring to something
totally different. It was my misremembering of the Windows API that led me
to mistakenly believe that the same limitation would apply on the
environment variable.

It's really sort of beside the point in this discussion anyway but I add
this note here for future reference.  It seems that we were both sort of
right but Bruce was more right than I in this context. It's a moot question
anyway since I've modified the CNG installer to put Elixir in the path
anyway.



On Wed, Sep 16, 2015 at 12:55 PM, Bruce Eckel <notifications@github.com>
wrote:

> The path length appears to be 2047, with 4095 for Windows 7 and later:
>
> https://software.intel.com/en-us/articles/limitation-to-the-length-of-the-system-path-variable
>
> I'm not suggesting whether it be iex or ielixir; just that, once the user
> does an installation, whatever the documentation says should work without
> additional adjustments to the path.
>
>
> -- Bruce Eckel
> www.MindviewInc.com <http://www.mindviewinc.com/>
> Blog: BruceEckel.github.io
> www.WinterTechForum.com
> www.AtomicScala.com
> www.Reinventing-Business.com
> http://www.TrustOrganizations.com <http://www.ScalaSummit.com>
>
>
> On Wed, Sep 16, 2015 at 7:47 AM, Onorio Catenacci <
> notifications@github.com>
> wrote:
>
> > I'm always glad to do what I can to help Jose.
> >
> > Take a look at my announcement of the CNG package on Elixir Lang Talk. We
> > need to explicitly document that someone needs to type the string
> "iex.bat"
> > at a command prompt because on Windows normally you can run a batch file
> > without having to type the extension. That is a Windows user would expect
> > to type "iex" (no extension) and have it run iex.bat. We've just changed
> > it such that someone will need to type "iex.bat" (with the extension).
> > It's down to making it clear that they will need to type the extension
> > which they normally wouldn't.
> >
> > --
> > Onorio
> >
> >
> > On Wed, Sep 16, 2015 at 9:37 AM, José Valim <notifications@github.com>
> > wrote:
> >
> > > 3.) If you want me to modify the docs to specify "iex.bat" for Windows,
> > > just let me know. I can do a PR when I get a chance.
> > >
> > > We already do this but maybe we should be clearer.
> > > I don't know what to change though.
> > >
> > > Thanks for all the changes and improvements Onorio!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140744832
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Onorio Catenacci
> >
> > http://onor.io
> > http://www.google.com/+OnorioCatenacci
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140747172
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/issues/599#issuecomment-140802499>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci
